version: '3.8'
services:
  app:
    build: .
    volumes:
      - /app:/src/app
    ports:
      - '3000:3000'
    environment:
      - PORT=3000
      

networks:
  jsphpapp:
    external: false